### ISSUE TITLE
Using ROS_QT_GUI in ROS Melodic

### ISSUE THREAD

**Issue by jptalledo10** [WelinLee/ROS_QT_GUI#1]
when running catkin_make on ROS melodic. a dependecy qt-build is missing which does not exist for ROS Melodic. Any workaround?

**Comment by WelinLee** [comment]
Sorry for late reply. According to the official website (http://wiki.ros.org/qt_build), qt_build package is not available on ROS melodic distribution. You could refer to qt_ros_test package in ROS_QT_GUI repository, which is more flexible for developing. Thanks.

**Comment by WelinLee** [comment]
> when running catkin_make on ROS melodic. a dependecy qt-build is missing which does not exist for ROS Melodic. Any workaround?

**Comment by WelinLee** [comment]
Hi, I also met the problem in Melodic distribution. I found that the moc file is not generated in Qt5.9.8, https://doc.qt.io/qt-5.9/cmake-manual.html. So I changed some rules in CMakeLists.txt as below:

qt5_wrap_cpp(MOC src/qt_ros_test.h)
qt5_generate_moc(src/qt_ros_test.h qt_ros_test.moc)
qt5_wrap_ui(UIC src/qt_ros_test.ui)
add_executable(${PROJECT_NAME}_node src/main.cpp src/qt_ros_test.cpp ${MOC} ${UIC} qt_ros_test.moc)

Remember to set the Qt5_DIR as you installed, such as set(Qt5_DIR "/home/user/Qt5.9.8/5.9.8/gcc/lib/cmake/Qt5").

It works.

**Comment by schokkobaer** [comment]
Yeah it works:) 
Thank you

**Comment by jptalledo10** [comment]
I will give it a try. For earlier isssue, I switched to another solution

**Comment by suho0515** [comment]
> Hi, I also met the problem in Melodic distribution. I found that the moc file is not generated in Qt5.9.8, https://doc.qt.io/qt-5.9/cmake-manual.html. So I changed some rules in CMakeLists.txt as below:
> 
> qt5_wrap_cpp(MOC src/qt_ros_test.h)
> qt5_generate_moc(src/qt_ros_test.h qt_ros_test.moc)
> qt5_wrap_ui(UIC src/qt_ros_test.ui)
> add_executable(${PROJECT_NAME}_node src/main.cpp src/qt_ros_test.cpp ${MOC} ${UIC} qt_ros_test.moc)
> 
> Remember to set the Qt5_DIR as you installed, such as set(Qt5_DIR "/home/user/Qt5.9.8/5.9.8/gcc/lib/cmake/Qt5").
> 
> It works.

Thanks for your help.

I Worte some tutorial to use your package with ROS Melodic.
Just reffer it if anyone need.

[https://velog.io/@suho0515/Test-PyQT-with-ROS-Melodic](url)

**Comment by WelinLee** [comment]
Hi Suho, thanks for you tutorial, that is great. If it is possible to contribute your factor code demo to this repository that support ROS Qt Melodic version?
Thanks.

**Comment by suho0515** [comment]
> Hi Suho, thanks for you tutorial, that is great. If it is possible to contribute your factor code demo to this repository that support ROS Qt Melodic version? Thanks.

sorry for late reply,
I checked the reply now!
is there anything i can help?

**Comment by WelinLee** [comment]
Currently not, thanks.

**Comment by WelinLee** [comment]
Currently not, thanks.
