### ISSUE TITLE
Qt的connect问题

### ISSUE THREAD

**Issue by HaoQChen** [WelinLee/ROS_QT_GUI#2]
Qt的connect最后有个参数决定着SLOT在哪个线程执行，不知道您有没有注意到？像[dyn_cfg_gui/src/dyn_cfg_gui.cpp](https://github.com/WelinLee/ROS_QT_GUI/blob/master/dyn_cfg_gui/src/dyn_cfg_gui.cpp)这里，SLOT将在主线程执行。您的设计思路是子线程只执行ROS的事件循环`ros::spinOnce();`吗？

**Comment by WelinLee** [comment]
您好，是的。一般qt界面是主线程，跟ros相关的操作另外开一个线程去处理。参考https://github.com/stonier/qt_ros

**Comment by zhihaoLee1** [comment]
welin你好，我用catkin_create_qt_pkg生成的qtGUI文件，然后把它的cmakelist文件导入到qtcreator文件中，总是报错，能说下您的联系方式么，想请教下这个环境变量怎么配置，这个问题困扰我好久了，谢谢。

**Comment by WelinLee** [comment]
您好，可以参见https://blog.csdn.net/u014610460/article/details/79355533这个博文。

**Comment by WelinLee** [comment]
您好，可以参见[](https://blog.csdn.net/u014610460/article/details/79355533)  这篇博文。

**Comment by WelinLee** [comment]
您好，具体报什么错？可以参见https://blog.csdn.net/u014610460/article/details/79355533  这篇博文。

**Comment by zhihaoLee1** [comment]
使用第一种方法解决问题了，多谢~~！！
