### ISSUE TITLE
Could not find roscpp

### ISSUE THREAD

**Issue by BobbleLaw** [WelinLee/ROS_QT_GUI#3]
Hi, thanks for your summary, it's very helpful.
Stand alone "ros_cmake" is what I am interested in. However, there's one problem when I configured the QtCreator environment. All the steps are instructed by ROS IDE wiki, and I also changed the .desktop file to bash the PATH (this fix catkinConfig.cmake problem). But I still get the error of "Could not find roscpp". 
Do you any idea how to fix that?

**Comment by WelinLee** [comment]
May I know which ros distribution are you using? Your encounter may hanppen in ROS MELODIC. If this, try ROS Qt Creator Plug-in (https://ros-qtc-plugin.readthedocs.io) instead.

**Comment by BobbleLaw** [comment]
ROS Kinetic it is. I tried ros-qtc-plugin too, still can't work.

**Comment by WelinLee** [comment]
In ROS Kinetic it should work. You could find the qt.desktop (or Digia.desktop) file in /usr/share/applications or ~/.local/share/applications. Copy it to the home directory and change it to executable by using chmod +x. Modify the qt.desktop ([Exec] = bash -i -c ...).
